APP_NAME=gofer

# ## Usage
usage :
	@echo ''
	@echo '$(APP_NAME)'
	@echo '---------------------------'
	@echo ''
	@echo 'Core tasks           : Description'
	@echo '-------------------- : -----------'
	@echo 'make all             : Clean slate to run tests'
	@echo 'make clean           : Remove all files generated by make tasks'
	@echo 'make setup           : Install depenendencies for development'
	@echo 'make build           : Recompile coffeescript'
	@echo 'make test            : Run tests (implicitly builds)'
	@echo ''
	@echo 'Additional tasks     : Description'
	@echo '-------------------- : -----------'
	@echo 'make release         : Publish version-tag matching package.json'
	@echo ''

.PHONY : check-checkout-clean test clean

all: clean setup test check-checkout-clean

clean:
	rm -rf lib node_modules

setup:
	npm install

build:
	@./node_modules/.bin/coffee -cbo lib src
	@./node_modules/.bin/npub prep lib

prepublish:
	./node_modules/.bin/npub prep

test: build
	NODE_ENV=test node_modules/.bin/mocha

# This will fail if there are unstaged changes in the checkout
check-checkout-clean:
	git diff --exit-code

.PHONY: release release-patch release-minor release-major

VERSION = $(shell node -pe 'require("./package.json").version')
release-patch: NEXT_VERSION = $(shell node -pe 'require("semver").inc("$(VERSION)", "patch")')
release-minor: NEXT_VERSION = $(shell node -pe 'require("semver").inc("$(VERSION)", "minor")')
release-major: NEXT_VERSION = $(shell node -pe 'require("semver").inc("$(VERSION)", "major")')
release-patch: release
release-minor: release
release-major: release

release: all
	@printf "Current version is $(VERSION). This will publish version $(NEXT_VERSION). Press [enter] to continue." >&2
	@read
	node -e '\
		var j = require("./package.json");\
		j.version = "$(NEXT_VERSION)";\
		var s = JSON.stringify(j, null, 2)+"\n";\
		require("fs").writeFileSync("./package.json", s);'
	git commit package.json -m 'Version $(NEXT_VERSION)'
	git tag -a "v$(NEXT_VERSION)" -m "Version $(NEXT_VERSION)"
	git push --tags origin HEAD:master
	npm publish
