APP_NAME=gofer
SRC = $(shell find src -name "*.coffee" -type f | sort)
LIB = $(SRC:src/%.coffee=lib/%.js)

COFFEE=node_modules/.bin/coffee --js

# ## Usage
usage :
	@echo ''
	@echo '$(APP_NAME)'
	@echo '---------------------------'
	@echo ''
	@echo 'Core tasks           : Description'
	@echo '-------------------- : -----------'
	@echo 'make all             : Clean slate to run tests'
	@echo 'make clean           : Remove all files generated by make tasks'
	@echo 'make setup           : Install depenendencies for development'
	@echo 'make build           : Recompile coffeescript'
	@echo ''
	@echo 'Additional tasks     : Description'
	@echo '-------------------- : -----------'
	@echo 'make release-patch   : Publish patch version bump'
	@echo 'make release-minor   : Publish minor version bump'
	@echo 'make release-major   : Publish major version bump'
	@echo ''

.PHONY : all setup clean build

all: clean setup
	npm test

clean:
	rm -rf node_modules

setup:
	npm install

build: $(LIB)
	@./node_modules/.bin/npub prep

lib/%.js: src/%.coffee
	dirname "$@" | xargs mkdir -p
	$(COFFEE) <"$<" >"$@"

release-%: clean setup
	./node_modules/.bin/npub publish $(subst release-,,$@)
