// Generated by CoffeeScript 1.9.0

/*
Copyright (c) 2014, Groupon, Inc.
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions
are met:

Redistributions of source code must retain the above copyright notice,
this list of conditions and the following disclaimer.

Redistributions in binary form must reproduce the above copyright
notice, this list of conditions and the following disclaimer in the
documentation and/or other materials provided with the distribution.

Neither the name of GROUPON nor the names of its contributors may be
used to endorse or promote products derived from this software without
specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS
IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED
TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
var GOOD_FORM_ENCODED, Gofer, Hub, applyBaseUrl, buildUserAgent, cleanObject, extend, isJsonResponse, merge, parseDefaults, resolveOptional, safeParseJSON, _ref, _ref1,
  __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

extend = require('lodash').extend;

Hub = require('./hub');

_ref = require('./helpers'), resolveOptional = _ref.resolveOptional, parseDefaults = _ref.parseDefaults, applyBaseUrl = _ref.applyBaseUrl, buildUserAgent = _ref.buildUserAgent, merge = _ref.merge, cleanObject = _ref.cleanObject;

_ref1 = require('./json'), safeParseJSON = _ref1.safeParseJSON, isJsonResponse = _ref1.isJsonResponse;

GOOD_FORM_ENCODED = 'application/x-www-form-urlencoded; charset=utf-8';

Gofer = (function() {
  function Gofer(config, _at_hub) {
    this.hub = _at_hub;
    this.request = __bind(this.request, this);
    this._rawConfig = config;
    this._defaults = this._endpointDefaults = null;
    if (this.hub == null) {
      this.hub = Hub();
    }
  }

  Gofer.prototype._initDefaults = function() {
    var _ref2;
    _ref2 = parseDefaults(this._rawConfig, this.serviceName), this._defaults = _ref2.defaults, this._endpointDefaults = _ref2.endpointDefaults;
    return this._rawConfig = null;
  };

  Gofer.prototype["with"] = function(overrides) {
    var copy, endpointDefaults, endpointName, _ref2;
    copy = new this.constructor({}, this.hub);
    copy.defaults = merge(this.defaults, overrides);
    copy.endpointDefaults = {};
    _ref2 = this.endpointDefaults;
    for (endpointName in _ref2) {
      endpointDefaults = _ref2[endpointName];
      copy.endpointDefaults[endpointName] = merge(endpointDefaults, overrides);
    }
    return copy;
  };

  Gofer.prototype.clone = function() {
    return this["with"]({});
  };

  Gofer.prototype.request = function(uri, options, cb) {
    var _ref2;
    _ref2 = resolveOptional(uri, options, cb), options = _ref2.options, cb = _ref2.cb;
    return this._request(options, cb);
  };

  Gofer.prototype.put = function(uri, options, cb) {
    var _ref2;
    _ref2 = resolveOptional(uri, options, cb), options = _ref2.options, cb = _ref2.cb;
    options.method = 'PUT';
    return this._request(options, cb);
  };

  Gofer.prototype.del = function(uri, options, cb) {
    var _ref2;
    _ref2 = resolveOptional(uri, options, cb), options = _ref2.options, cb = _ref2.cb;
    options.method = 'DELETE';
    return this._request(options, cb);
  };

  Gofer.prototype.head = function(uri, options, cb) {
    var _ref2;
    _ref2 = resolveOptional(uri, options, cb), options = _ref2.options, cb = _ref2.cb;
    options.method = 'HEAD';
    return this._request(options, cb);
  };

  Gofer.prototype.post = function(uri, options, cb) {
    var _ref2;
    _ref2 = resolveOptional(uri, options, cb), options = _ref2.options, cb = _ref2.cb;
    options.method = 'POST';
    return this._request(options, cb);
  };

  Gofer.prototype.patch = function(uri, options, cb) {
    var _ref2;
    _ref2 = resolveOptional(uri, options, cb), options = _ref2.options, cb = _ref2.cb;
    options.method = 'PATCH';
    return this._request(options, cb);
  };

  Gofer.prototype.registerEndpoint = function(endpointName, endpointFn) {
    Object.defineProperty(this, endpointName, {
      configurable: true,
      get: function() {
        var request, value;
        request = this.requestWithDefaults({
          endpointName: endpointName
        });
        value = endpointFn(request);
        Object.defineProperty(this, endpointName, {
          value: value
        });
        return value;
      }
    });
    return this;
  };

  Gofer.prototype.registerEndpoints = function(endpointMap) {
    var handler, name;
    for (name in endpointMap) {
      handler = endpointMap[name];
      this.registerEndpoint(name, handler);
    }
    return this;
  };

  Gofer.prototype.addOptionMapper = function(mapper) {
    this._mappers = this._mappers.concat([mapper]);
    return this;
  };

  Gofer.prototype.clearOptionMappers = function() {
    return this._mappers = [];
  };

  Gofer.prototype.requestWithDefaults = function(defaults) {
    return (function(_this) {
      return function(uri, options, cb) {
        var _ref2;
        _ref2 = resolveOptional(uri, options, cb), options = _ref2.options, cb = _ref2.cb;
        options = merge(defaults, options);
        return _this._request(options, cb);
      };
    })(this);
  };

  Gofer.prototype._getDefaults = function(defaults, options) {
    var endpointName;
    endpointName = options.endpointName;
    if ((endpointName != null) && (this.endpointDefaults[endpointName] != null)) {
      defaults = merge(defaults, this.endpointDefaults[endpointName]);
    }
    return defaults;
  };

  Gofer.prototype.applyBaseUrl = applyBaseUrl;

  Gofer.prototype._applyMappers = function(originalOptions) {
    return this._mappers.reduce((function(_this) {
      return function(options, mapper) {
        return mapper.call(_this, options);
      };
    })(this), originalOptions);
  };

  Gofer.prototype._request = function(options, cb) {
    var defaults, err, req, _base, _ref2;
    defaults = this._getDefaults(this.defaults, options);
    if (options.methodName == null) {
      options.methodName = ((_ref2 = options.method) != null ? _ref2 : 'get').toLowerCase();
    }
    if (this.serviceName != null) {
      options.serviceName = this.serviceName;
    }
    if (this.serviceVersion != null) {
      options.serviceVersion = this.serviceVersion;
    }
    try {
      options = this._applyMappers(merge(defaults, options));
    } catch (_error) {
      err = _error;
      return cb(err);
    }
    if (options.headers == null) {
      options.headers = {};
    }
    if ((_base = options.headers)['User-Agent'] == null) {
      _base['User-Agent'] = buildUserAgent(options);
    }
    if (options.qs != null) {
      options.qs = cleanObject(options.qs);
    }
    if (options.headers != null) {
      options.headers = cleanObject(options.headers);
    }
    if (options.logData == null) {
      options.logData = {};
    }
    extend(options.logData, {
      serviceName: options.serviceName,
      endpointName: options.endpointName,
      methodName: options.methodName,
      pathParams: options.pathParams
    });
    if (options.baseUrl) {
      delete options.baseUrl;
    }
    if (typeof cb === 'function') {
      req = this.hub.fetch(options, function(error, body, response, responseData) {
        var parseError, parseJSON, _ref3, _ref4;
        parseJSON = (_ref3 = options.parseJSON) != null ? _ref3 : isJsonResponse(response, body);
        if (parseJSON) {
          _ref4 = safeParseJSON(body, response), parseError = _ref4.parseError, body = _ref4.body;
        }
        if (error == null) {
          error = parseError;
        }
        return cb(error, body, responseData, response);
      });
    } else {
      req = this.hub.fetch(options);
    }
    if (options.form && options.forceFormEncoding !== false) {
      req.setHeader('Content-Type', GOOD_FORM_ENCODED);
    }
    return req;
  };

  Gofer.prototype._mappers = [
    function(opts) {
      var baseUrl;
      baseUrl = opts.baseUrl;
      if (baseUrl != null) {
        delete opts.baseUrl;
        return this.applyBaseUrl(baseUrl, opts);
      } else {
        return opts;
      }
    }
  ];

  return Gofer;

})();

Gofer.prototype.fetch = Gofer.prototype.request;

Gofer.prototype.get = Gofer.prototype.request;

Object.defineProperties(Gofer.prototype, {
  defaults: {
    enumerable: true,
    get: function() {
      if (!this._defaults) {
        this._initDefaults();
      }
      return this._defaults;
    },
    set: function(defaults) {
      return this._defaults = defaults;
    }
  },
  endpointDefaults: {
    enumerable: true,
    get: function() {
      if (!this._endpointDefaults) {
        this._initDefaults();
      }
      return this._endpointDefaults;
    },
    set: function(endpointDefaults) {
      return this._endpointDefaults = endpointDefaults;
    }
  }
});

module.exports = Gofer;

Gofer['default'] = Gofer;
